global using Microsoft.AspNetCore.Mvc;
global using CommandsService;
global using CommandsService.Models.Domain;
global using CommandsService.Models.External;
global using CommandsService.Extensions;
global using CommandsService.Persistence;
global using CommandsService.Persistence.Repository;
global using Microsoft.EntityFrameworkCore;
global using AutoMapper;
